# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    continuationIndentSize: 8
  ParameterListWrapping:
    indentSize: 4
  StringTemplate:
    active: false
  MaximumLineLength:
    active: false
  MultiLineIfElse:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false

complexity:
  LongParameterList:
    functionThreshold: 7
  LongMethod:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
      active: false